// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0QjDdhqU3M3e8jsDLX3UpNq1VY63vJPo',
    appId: '1:19643724169:web:6b6c2775bf5c7f9494b158',
    messagingSenderId: '19643724169',
    projectId: 'strideup-94d1a',
    authDomain: 'strideup-94d1a.firebaseapp.com',
    storageBucket: 'strideup-94d1a.appspot.com',
    measurementId: 'G-7V8DKRZE0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7S22TVErtc3kPMB26kHkMkfRVuQxxi78',
    appId: '1:19643724169:android:824c96501596fb0994b158',
    messagingSenderId: '19643724169',
    projectId: 'strideup-94d1a',
    storageBucket: 'strideup-94d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmlrC7LbYlQhE5_FoEkJJC50S6mQCDn5I',
    appId: '1:19643724169:ios:0d837605b791208c94b158',
    messagingSenderId: '19643724169',
    projectId: 'strideup-94d1a',
    storageBucket: 'strideup-94d1a.appspot.com',
    androidClientId: '19643724169-so98pfutmolo1428ep4sl527r60576ph.apps.googleusercontent.com',
    iosClientId: '19643724169-b4etihoevm030ec7g2qt03t03mq2sjvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.strideUp',
  );

}